using PlayCEASharp.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlayCEASharp.Configuration
{
    /// <summary>
    /// The configuration used to model the relation of brackets for a League.
    /// This configuration is generated by the ConfigurationGenerator at runtime.
    /// </summary>
    internal class BracketConfiguration
    {
        /// <summary>
        /// The lists of bracketIds that comprise the bracket sets for the league.
        /// </summary>
        internal string[][] bracketSets { get; set; }

        /// <summary>
        /// Mapping from roundName => stageName for each round.
        /// </summary>
        internal Dictionary<string, string> stageConfiguration { get; set; }

        /// <summary>
        /// The collection of stage groups for each stage.
        /// </summary>
        internal StageGroup[] stageGroups { get; set; }
    }
}
